<template>
  <div class="export-actions">
    <ActionButton
      intent="print"
      icon="print"
      :label="t('common.print')"
      :tooltip="t('common.printTooltip')"
      :loading="printing"
      :disable="isEmpty || busy"
      @click="doPrint"
    />
    <ActionButton
      intent="pdf"
      icon="picture_as_pdf"
      :label="t('common.pdf')"
      :tooltip="t('common.pdfTooltip')"
      :loading="pdfing"
      :disable="isEmpty || busy"
      @click="doPdf"
    />
    <!-- Excel is ALWAYS green with a spreadsheet icon (design-system rule). -->
    <ActionButton
      intent="excel"
      icon="mdi-microsoft-excel"
      :label="t('common.excel')"
      :tooltip="t('common.excelTooltip')"
      :loading="exceling"
      :disable="isEmpty || busy"
      data-cy="export-excel"
      @click="doExcel"
    />
  </div>
</template>

<script setup>
/**
 * Print / PDF / Excel for the current table view, as three enterprise buttons.
 *
 * The colours come from the action-intent system, so the rule "Export to Excel
 * is green with a spreadsheet icon" is enforced everywhere the component is
 * used. Each button owns its loading state and is disabled while any export is
 * running, so a double click can never start two downloads of the same report.
 */
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import ActionButton from './ActionButton.vue'
import { downloadExcel, downloadPdf, exportFilename, printArea } from 'src/utils/export'
import { notify } from 'src/utils/notify'

const props = defineProps({
  rows: { type: Array, default: () => [] },
  columns: { type: Array, default: () => [] },
  filename: { type: String, default: 'Report' },
  title: { type: String, default: '' },
  printSelector: { type: String, default: '.print-area' },
  /**
   * Optional report header written into every exported file and the print
   * view — `[{ label, value }]` (period, applied filters, generated by …).
   */
  meta: { type: Array, default: () => [] },
})

const { t } = useI18n()

const printing = ref(false)
const pdfing = ref(false)
const exceling = ref(false)
const busy = computed(() => printing.value || pdfing.value || exceling.value)
const isEmpty = computed(() => !props.rows?.length)

const reportTitle = computed(() => props.title || props.filename)
const baseFilename = computed(() => exportFilename(props.filename))

const exportColumns = () => (props.columns || []).filter((c) => c.name !== 'actions' && c.name !== 'select')

function doPrint() {
  if (busy.value) return
  printing.value = true
  try {
    printArea(props.printSelector, { title: reportTitle.value, meta: props.meta })
  } catch (e) {
    notify.error(e.message || t('common.exportFailed'))
  } finally {
    printing.value = false
  }
}

async function doPdf() {
  if (busy.value) return
  pdfing.value = true
  try {
    const cols = exportColumns()
    await downloadPdf(baseFilename.value, props.rows, cols.length ? cols : null, { title: reportTitle.value, meta: props.meta })
    notify.success(t('common.pdfExported'))
  } catch (e) {
    notify.error(e.message || t('common.exportFailed'))
  } finally {
    pdfing.value = false
  }
}

async function doExcel() {
  if (busy.value) return
  exceling.value = true
  try {
    const cols = exportColumns()
    await downloadExcel(baseFilename.value, props.rows, cols.length ? cols : null, { sheetName: reportTitle.value, meta: props.meta })
    notify.success(t('common.excelExported'))
  } catch (e) {
    notify.error(e.message || t('common.exportFailed'))
  } finally {
    exceling.value = false
  }
}
</script>

<style lang="sass" scoped>
.export-actions
  display: flex
  align-items: center
  gap: 8px
  flex-wrap: wrap
</style>
